apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-app-v2
  template:
    metadata:
      labels:
        app: prom-app-v2
    spec:
      containers:
        - name: prom-containers
          image: nobislan/first-prom:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
