apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-app-v1
  template:
    metadata:
      labels:
        app: prom-app-v1
    spec:
      containers:
        - name: prom-containers
          image: nobislan/first-prom:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
