apiVersion: v1
kind: Service
metadata:
  name: prom-service-v2
spec:
  type: NodePort
  ports:
    - name: "prom-port-v2"
      protocol: "TCP"
      port: 8080
      nodePort: 30091
  selector:
    app: prom-app-v2
