apiVersion: v1
kind: Service
metadata:
  name: prom-service-v1
spec:
  type: NodePort
  ports:
    - name: "prom-port-v1"
      protocol: "TCP"
      port: 8080
      nodePort: 30090
  selector:
    app: prom-app-v1
